path_to_ir_design: "/mnt/more/Documents/xls/bazel-bin/xls/modules/rle/rle_enc_opt_ir.opt.ir"
dma_sm_config {
  base_address: 0x0
  stream_channels {
    ir_name: "rle_enc__input_r";
    DMA_ID: 0;
  }
  stream_channels {
    ir_name: "rle_enc__output_s";
    DMA_ID: 1;
  }
}
