path_to_ir_design: "/mnt/more/Documents/xls/bazel-bin/xls/modules/rle/rle_enc_opt_ir.opt.ir"
sm_config {
  base_address: 0x0
  stream_channels {
    ir_name: "rle_enc__input_r";
    in_manager_offset: 0x0;
  }
  stream_channels {
    ir_name: "rle_enc__output_s";
    in_manager_offset: 0x400;
  }
}
